// Code generated by "stringer -type=RelationType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RelationProcessorCore-0]
	_ = x[RelationNumaNode-1]
	_ = x[RelationCache-2]
	_ = x[RelationProcessorPackage-3]
	_ = x[RelationGroup-4]
	_ = x[RelationProcessorDie-5]
	_ = x[RelationNumaNodeEx-6]
	_ = x[RelationProcessorModule-7]
}

const _RelationType_name = "RelationProcessorCoreRelationNumaNodeRelationCacheRelationProcessorPackageRelationGroupRelationProcessorDieRelationNumaNodeExRelationProcessorModule"

var _RelationType_index = [...]uint8{0, 21, 37, 50, 74, 87, 107, 125, 148}

func (i RelationType) String() string {
	if i < 0 || i >= RelationType(len(_RelationType_index)-1) {
		return "RelationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RelationType_name[_RelationType_index[i]:_RelationType_index[i+1]]
}
